[versions]
appcompat = "1.7.1"
appauth = "0.11.1"
jwksRsa = "0.23.0"
javaJwt = "4.5.0"
ktor = "3.3.1"
javaUuidGenerator = "5.1.1"
opentelemetryBom = "1.55.0"
browser = "1.9.0"
kotlinxCoroutinesTest = "1.10.2"

[libraries]
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

appauth = {group = "net.openid", name="appauth", version.ref = "appauth"}
java-jwt = { group = "com.auth0", name = "java-jwt", version.ref = "javaJwt" }
jwks-rsa = { group = "com.auth0", name = "jwks-rsa", version.ref = "jwksRsa" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

opentelemetry-bom = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "opentelemetryBom" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api" }
opentelemetry-extension-kotlin = { module = "io.opentelemetry:opentelemetry-extension-kotlin" }
opentelemetry-sdk = { module = "io.opentelemetry:opentelemetry-sdk" }
java-uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "javaUuidGenerator" }

kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest"}
