on: push

# Replace old runs in the same group
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_criiptoDomain: ${{ secrets.CRIIPTO_VERIFY_DOMAIN }}
  ORG_GRADLE_PROJECT_criiptoClientId: ${{ secrets.CRIIPTO_VERIFY_CLIENT_ID }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Run check
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: check
      - name: Run unit tests
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: test